#server:
#  port: 8081
#  
#  
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/account
#    username: postgres
#    password: postgres
#    
#    
#    
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql : true
#    hibernate:
#      ddl-auto: update  
#    properties:
#      hibernate:
#        format_sql: true